# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano_v2
    shield: settings_reset

  - board: nice_nano_v2
    shield: pipar_flake
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: pipar_flake_zmk_studio
